### ISSUE TITLE
在node.js中使用时会有报错

### ISSUE THREAD

**Issue by aylanbrown** [yiminghe/async-validator#207]
我用node.js + koa + async-validator进行开发，回调函数的形式无法执行

如果用Promise的形式调用有两个问题

1. 如果按照文档给出的`{ errors, fields }`在控制台打印则是`undefined undefined`
2. 在catch句柄上直接使用形参则会在控制台提示`source.hasOwnProperty is not a function`的错误

![image](https://user-images.githubusercontent.com/17047207/70768270-603f7b00-1d9f-11ea-9685-9aed09522f75.png)

```
Promise {
  <rejected> TypeError: source.hasOwnProperty is not a function
    at Object.required (D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:279:33)
    at Object.required$1 [as validator] (D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:895:9)
    at D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:1298:20
    at D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:139:5
    at Array.forEach (<anonymous>)
    at asyncParallelArray (D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:138:7)
    at D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:226:9
    at Array.forEach (<anonymous>)
    at D:\new_koa\utils\node_modules\async-validator\dist-node\index.js:220:16
    at new Promise (<anonymous>) }
```

**Comment by ygj6** [comment]
In my environment can't eproduce your problem.Can you provide more detailed information?

**Comment by aylanbrown** [comment]
服务端的代码：
```
const Koa = require('koa')
const Router = require('koa-router')
const { default: Schema } = require('async-validator')

const app = new Koa()
const router = Router()

router.get('/', (ctx, next) => {

	let query  = ctx.query,
			schema = new Schema({
				name: [
					{ require: true, message: 'name is required character' }
				]
			})

	schema.validate(query, (error, field) => {

		console.log('callback', error, field)
	})

	schema.validate(query)
	.then(() => {

		console.log('validate is pass')
	})
	.catch((error) => {

		console.log('validate error', error)
	})

	ctx.body = 'Hello World'
})


app.use(router.routes()).use(router.allowedMethods())


app.listen(8080, () => console.log('Server is runing in port 8080'))
```
callback回调形式的代码并没有被打印

控制台报错：
```
validate error TypeError: source.hasOwnProperty is not a function
    at Object.string [as validator] (D:\new_koa\node_modules\async-validator\dist-node\index.js:525:60)
    at D:\new_koa\node_modules\async-validator\dist-node\index.js:1298:20
    at D:\new_koa\node_modules\async-validator\dist-node\index.js:139:5
    at Array.forEach (<anonymous>)
    at asyncParallelArray (D:\new_koa\node_modules\async-validator\dist-node\index.js:138:7)
    at D:\new_koa\node_modules\async-validator\dist-node\index.js:226:9
    at Array.forEach (<anonymous>)
    at D:\new_koa\node_modules\async-validator\dist-node\index.js:220:16
    at new Promise (<anonymous>)
    at asyncMap (D:\new_koa\node_modules\async-validator\dist-node\index.js:206:17)

```

**Comment by ygj6** [comment]
I took the time to run your code and still gave no error. 
Is it possible that the node version is caused?
I'm using `Nodejs 12.13.1`, maybe you can try this version.

**Comment by aylanbrown** [comment]
@ygj6 I update Node.js 12.13.1，and it also error

**Comment by ygj6** [comment]
Is it convenient to provide client code to determine the value of `ctx.query`, because I found that your `ctx.query` type is: `[Object: null prototype] {}`, there is no `__proto__` pointing to the prototype object (`Object.prototype`), so If `Object.prototype.hasOwnProperty ()` is not found, an error will be reported. I personally think that the `Koa` framework has rewritten the object prototype, and the `ctx.query `is no longer a native object.

**Comment by aylanbrown** [comment]
@ygj6 thanks, I try Object has `__proto__` is pass
